using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Web.Script.Serialization;

namespace Wenta
{
    /// <summary>Identity that belongs to a drawn component but not to the
    /// physics model: a stable GUID (so a re-imported drawing keeps its
    /// component identities) and the drawing scope it came from (reserved
    /// for multi-drawing work; null for now). Kept in a side table keyed by
    /// component id because <see cref="Component"/> carries neither.</summary>
    public sealed class ComponentMeta
    {
        /// <summary>Stable identifier, "D"-format GUID string. Generated by
        /// <see cref="NetworkJson.Serialize"/> when missing; round-tripped
        /// verbatim otherwise.</summary>
        public string Guid;

        /// <summary>Reserved: which drawing/model space the component was
        /// read from. Null until multi-drawing support lands.</summary>
        public string DrawingScope;
    }

    /// <summary>Versioned JSON (de)serialisation of a <see cref="Network"/>
    /// (issue #46, library half). Same toolchain as <see cref="ZetaCatalog"/>:
    /// <c>System.Web.Script.Serialization.JavaScriptSerializer</c> over a
    /// Dictionary/ArrayList tree, no NuGet.
    ///
    /// Format (snake_case, schema_version 1):
    /// {
    ///   "schema_version": 1,
    ///   "name": "tee",
    ///   "components": [
    ///     { "id": "ahu",  "wenta_class": "Source", "guid": "…", "drawing_scope": null, "name": "AHU" },
    ///     { "id": "duct", "wenta_class": "RigidDuct", "guid": "…", "drawing_scope": null, "name": "duct",
    ///       "cross_section": { "shape": "round", "diameter": 0.315 },
    ///       "length": 20, "absolute_roughness": 0.0001 },
    ///     { "id": "tee",  "wenta_class": "Tee", …, "cross_section": { … },
    ///       "zeta_straight": 0.1, "zeta_branch": 0.4 },
    ///     { "id": "flex", "wenta_class": "FlexDuct", …, "diameter": 0.125, "length": 3,
    ///       "pressure_drop_per_meter": 2, "stretch_percentage": 100 },
    ///     { "id": "fit",  "wenta_class": "TwoPortFitting", …,
    ///       "cross_section": { "shape": "rectangular", "width": 0.4, "height": 0.2 }, "zeta": 0.3 },
    ///     { "id": "t1",   "wenta_class": "Terminal", …, "flowrate": 0.06, "zeta": 0 }
    ///   ],
    ///   "connections": [ { "from": "ahu.outlet", "to": "duct.inlet" }, … ]
    /// }
    ///
    /// Geometry is in metres, flows in m³/s, matching the C# constructors.
    /// Per-class fields are exactly the constructor arguments; optional
    /// constructor arguments may be omitted and take the constructor default.
    /// Field names follow the former Python pydantic schemas
    /// (<c>absolute_roughness</c>, <c>pressure_drop_per_meter</c>,
    /// <c>stretch_percentage</c>, <c>zeta_straight</c>, <c>zeta_branch</c>).
    /// Connection endpoints are "componentId.portName" (what
    /// <see cref="Network.Connect"/> accepts); a bare component id is accepted
    /// on input when the port is unambiguous, as is the legacy
    /// "componentId:portName" spelling. The legacy keys <c>type</c>,
    /// <c>source</c> and <c>target</c> are accepted as aliases for
    /// <c>wenta_class</c>, <c>from</c> and <c>to</c> on input only.</summary>
    public static class NetworkJson
    {
        /// <summary>Highest <c>schema_version</c> this build understands.
        /// <see cref="Parse(string, out Dictionary{string, ComponentMeta})"/>
        /// rejects newer documents. Adding optional fields does not bump it;
        /// renaming or removing fields does.</summary>
        public const int SchemaVersion = 1;

        // ---- write ---------------------------------------------------------

        /// <summary>Serialise <paramref name="net"/> to JSON. <paramref name="meta"/>
        /// (optional) supplies GUID / drawing scope per component id. Any
        /// component without a GUID gets a fresh one; when <paramref name="meta"/>
        /// is a writable dictionary the generated entries are written back into
        /// it so later saves reuse the same GUIDs.</summary>
        public static string Serialize(Network net, IDictionary<string, ComponentMeta> meta = null)
        {
            if (net == null)
                throw new WentaException("NetworkJson.Serialize: network is null");

            var root = new Dictionary<string, object>();
            root["schema_version"] = SchemaVersion;
            root["name"] = net.Name ?? "";
            var components = new ArrayList();
            var connections = new ArrayList();
            root["components"] = components;
            root["connections"] = connections;

            bool writeBack = meta != null && !meta.IsReadOnly;
            foreach (KeyValuePair<string, Component> kv in net.Components)
            {
                string cid = kv.Key;
                Component c = kv.Value;

                ComponentMeta m = null;
                if (meta != null) meta.TryGetValue(cid, out m);
                if (m == null)
                {
                    m = new ComponentMeta();
                    if (writeBack) meta[cid] = m;
                }
                if (string.IsNullOrEmpty(m.Guid))
                    m.Guid = System.Guid.NewGuid().ToString("D");

                components.Add(ComponentToDict(cid, c, m));

                // Component-to-component connections: every predecessor of an
                // in-port node is an out-port node "srcId:srcPort" (Network.Add
                // only ever wires in-port -> component and component -> out-port,
                // so nothing else can point at an in-port).
                foreach (Port p in c.Ports)
                {
                    if (!p.IsIn) continue;
                    foreach (string pred in net.Predecessors(Network.PortNodeId(cid, p.Name)))
                    {
                        int colon = pred.LastIndexOf(':');
                        if (colon < 0) continue;
                        var e = new Dictionary<string, object>();
                        e["from"] = pred.Substring(0, colon) + "." + pred.Substring(colon + 1);
                        e["to"] = cid + "." + p.Name;
                        connections.Add(e);
                    }
                }
            }

            var ser = new JavaScriptSerializer();
            ser.MaxJsonLength = int.MaxValue;
            return ser.Serialize(root);
        }

        /// <summary>Write <see cref="Serialize"/> output to <paramref name="path"/> (UTF-8).</summary>
        public static void Save(Network net, string path, IDictionary<string, ComponentMeta> meta = null)
        {
            File.WriteAllText(path, Serialize(net, meta));
        }

        // ---- read ----------------------------------------------------------

        /// <summary>Parse network JSON, discarding GUID / drawing-scope metadata.</summary>
        public static Network Parse(string json)
        {
            Dictionary<string, ComponentMeta> ignored;
            return Parse(json, out ignored);
        }

        /// <summary>Parse network JSON. <paramref name="meta"/> receives one
        /// entry per component (GUID / drawing scope as found in the file;
        /// null members when the file did not carry them). Throws
        /// <see cref="WentaException"/> for malformed JSON, a
        /// <c>schema_version</c> newer than <see cref="SchemaVersion"/> (or not a
        /// positive integer), a missing <c>components</c> array, a component
        /// without <c>id</c> or with an unknown <c>wenta_class</c>, a duplicate
        /// id, a missing or non-numeric required field, a malformed
        /// <c>cross_section</c>, or a connection naming an unknown component
        /// or port. Constructor range checks (e.g. negative length) surface
        /// unchanged as <see cref="WentaException"/>.</summary>
        public static Network Parse(string json, out Dictionary<string, ComponentMeta> meta)
        {
            var ser = new JavaScriptSerializer();
            ser.MaxJsonLength = int.MaxValue;
            Dictionary<string, object> root;
            try
            {
                root = ser.Deserialize<Dictionary<string, object>>(json);
            }
            catch (Exception ex)
            {
                throw new WentaException("invalid network JSON (" + ex.Message + ")");
            }
            if (root == null)
                throw new WentaException("invalid network JSON: empty document");

            int version = root.ContainsKey("schema_version") ? ParseVersion(root["schema_version"]) : 1;
            if (version > SchemaVersion)
                throw new WentaException("network JSON declares schema_version "
                    + version.ToString(CultureInfo.InvariantCulture)
                    + "; this build supports schema_version "
                    + SchemaVersion.ToString(CultureInfo.InvariantCulture) + " or older");

            object compsObj;
            if (!root.TryGetValue("components", out compsObj) || !(compsObj is ArrayList))
                throw new WentaException("network JSON has no 'components' array");

            var net = new Network();
            net.Name = Str(root, "name", "network") ?? "";
            meta = new Dictionary<string, ComponentMeta>();

            int index = 0;
            foreach (object o in (ArrayList)compsObj)
            {
                string at = "components[" + index.ToString(CultureInfo.InvariantCulture) + "]";
                var d = o as Dictionary<string, object>;
                if (d == null)
                    throw new WentaException("network JSON: " + at + " is not an object");
                string cid = Str(d, "id", at);
                if (string.IsNullOrEmpty(cid))
                    throw new WentaException("network JSON: " + at + " has no 'id'");
                if (net.Components.ContainsKey(cid))
                    throw new WentaException("network JSON: duplicate component id '" + cid + "'");
                string ctx = "component '" + cid + "'";
                string cls = Str(d, "wenta_class", ctx) ?? Str(d, "type", ctx);
                if (string.IsNullOrEmpty(cls))
                    throw new WentaException("network JSON: " + ctx + " has no 'wenta_class'");
                string name = Str(d, "name", ctx) ?? cid;

                net.Add(cid, BuildComponent(cls, name, d, ctx + " (" + cls + ")"));

                var m = new ComponentMeta();
                m.Guid = Str(d, "guid", ctx);
                m.DrawingScope = Str(d, "drawing_scope", ctx);
                meta[cid] = m;
                index++;
            }

            object connsObj;
            if (root.TryGetValue("connections", out connsObj) && connsObj != null)
            {
                var conns = connsObj as ArrayList;
                if (conns == null)
                    throw new WentaException("network JSON: 'connections' must be an array");
                index = 0;
                foreach (object o in conns)
                {
                    string at = "connections[" + index.ToString(CultureInfo.InvariantCulture) + "]";
                    var d = o as Dictionary<string, object>;
                    if (d == null)
                        throw new WentaException("network JSON: " + at + " is not an object");
                    string from = Str(d, "from", at) ?? Str(d, "source", at);
                    string to = Str(d, "to", at) ?? Str(d, "target", at);
                    if (string.IsNullOrEmpty(from) || string.IsNullOrEmpty(to))
                        throw new WentaException("network JSON: " + at + " needs both 'from' and 'to'");
                    net.Connect(Endpoint(from), Endpoint(to));
                    index++;
                }
            }
            return net;
        }

        /// <summary>Read a network JSON file; see <see cref="Parse(string, out Dictionary{string, ComponentMeta})"/>.</summary>
        public static Network Load(string path, out Dictionary<string, ComponentMeta> meta)
        {
            string json;
            try
            {
                json = File.ReadAllText(path);
            }
            catch (Exception ex)
            {
                throw new WentaException("cannot read network JSON '" + path + "': " + ex.Message);
            }
            return Parse(json, out meta);
        }

        // ---- component <-> dictionary -----------------------------------------

        /// <summary>Type discriminator written to <c>wenta_class</c>.</summary>
        public static string WentaClassOf(Component c)
        {
            if (c is Source) return "Source";
            if (c is RigidDuct) return "RigidDuct";
            if (c is FlexDuct) return "FlexDuct";
            if (c is Terminal) return "Terminal";
            if (c is TwoPortFitting) return "TwoPortFitting";
            if (c is Tee) return "Tee";
            throw new WentaException("NetworkJson: unsupported component type "
                + (c == null ? "null" : c.GetType().Name));
        }

        private static Dictionary<string, object> ComponentToDict(string cid, Component c, ComponentMeta m)
        {
            var d = new Dictionary<string, object>();
            d["id"] = cid;
            d["wenta_class"] = WentaClassOf(c);
            d["guid"] = m.Guid;
            d["drawing_scope"] = m.DrawingScope;
            d["name"] = c.Name;

            var rd = c as RigidDuct;
            if (rd != null)
            {
                d["cross_section"] = CrossSectionToDict(rd.CrossSection);
                d["length"] = rd.Length;
                d["absolute_roughness"] = rd.AbsoluteRoughness;
                return d;
            }
            var fd = c as FlexDuct;
            if (fd != null)
            {
                d["diameter"] = fd.Diameter;
                d["length"] = fd.Length;
                d["pressure_drop_per_meter"] = fd.PressureDropPerMeter;
                d["stretch_percentage"] = fd.StretchPercentage;
                return d;
            }
            var t = c as Terminal;
            if (t != null)
            {
                d["flowrate"] = t.Flowrate;
                if (t.CrossSection != null) d["cross_section"] = CrossSectionToDict(t.CrossSection);
                d["zeta"] = t.Zeta;
                return d;
            }
            var f = c as TwoPortFitting;
            if (f != null)
            {
                d["cross_section"] = CrossSectionToDict(f.CrossSection);
                d["zeta"] = f.Zeta;
                return d;
            }
            var tee = c as Tee;
            if (tee != null)
            {
                d["cross_section"] = CrossSectionToDict(tee.CrossSection);
                d["zeta_straight"] = tee.ZetaStraight;
                d["zeta_branch"] = tee.ZetaBranch;
                return d;
            }
            return d; // Source: identity fields only
        }

        private static Dictionary<string, object> CrossSectionToDict(CrossSection cs)
        {
            if (cs == null)
                throw new WentaException("NetworkJson: component has no cross-section");
            var d = new Dictionary<string, object>();
            var r = cs as Round;
            if (r != null)
            {
                d["shape"] = "round";
                d["diameter"] = r.Diameter;
                return d;
            }
            var rect = cs as Rectangular;
            if (rect != null)
            {
                d["shape"] = "rectangular";
                d["width"] = rect.Width;
                d["height"] = rect.Height;
                return d;
            }
            throw new WentaException("NetworkJson: unsupported cross-section type " + cs.GetType().Name);
        }

        private static Component BuildComponent(string cls, string name, Dictionary<string, object> d, string ctx)
        {
            switch (cls)
            {
                case "Source":
                    return new Source(name);
                case "RigidDuct":
                    return new RigidDuct(name,
                        RequireCrossSection(d, ctx),
                        RequireDouble(d, "length", ctx),
                        OptionalDouble(d, "absolute_roughness", 0.0001, ctx));
                case "FlexDuct":
                    return new FlexDuct(name,
                        RequireDouble(d, "diameter", ctx),
                        RequireDouble(d, "length", ctx),
                        RequireDouble(d, "pressure_drop_per_meter", ctx),
                        OptionalDouble(d, "stretch_percentage", 100.0, ctx));
                case "Terminal":
                    return new Terminal(name,
                        RequireDouble(d, "flowrate", ctx),
                        OptionalCrossSection(d, ctx),
                        OptionalDouble(d, "zeta", 0.0, ctx));
                case "TwoPortFitting":
                    return new TwoPortFitting(name,
                        RequireCrossSection(d, ctx),
                        RequireDouble(d, "zeta", ctx));
                case "Tee":
                    return new Tee(name,
                        RequireCrossSection(d, ctx),
                        OptionalDouble(d, "zeta_straight", 0.0, ctx),
                        OptionalDouble(d, "zeta_branch", 0.5, ctx));
                default:
                    throw new WentaException("network JSON: " + ctx + ": unknown wenta_class '" + cls + "'");
            }
        }

        private static CrossSection RequireCrossSection(Dictionary<string, object> d, string ctx)
        {
            object v;
            if (!d.TryGetValue("cross_section", out v) || v == null)
                throw new WentaException("network JSON: " + ctx + " has no 'cross_section'");
            return ParseCrossSection(v, ctx);
        }

        private static CrossSection OptionalCrossSection(Dictionary<string, object> d, string ctx)
        {
            object v;
            if (!d.TryGetValue("cross_section", out v) || v == null) return null;
            return ParseCrossSection(v, ctx);
        }

        private static CrossSection ParseCrossSection(object v, string ctx)
        {
            var d = v as Dictionary<string, object>;
            if (d == null)
                throw new WentaException("network JSON: " + ctx + ": 'cross_section' must be an object");
            string inner = ctx + " cross_section";
            string shape = Str(d, "shape", inner);
            if (shape == "round")
                return new Round(RequireDouble(d, "diameter", inner));
            if (shape == "rectangular")
                return new Rectangular(RequireDouble(d, "width", inner), RequireDouble(d, "height", inner));
            throw new WentaException("network JSON: " + inner
                + ": 'shape' must be 'round' or 'rectangular', got '" + (shape ?? "null") + "'");
        }

        // ---- helpers -----------------------------------------------------------

        /// <summary>"a.b" passes through; legacy "a:b" becomes "a.b"; a bare id
        /// passes through (Network.Connect resolves the unambiguous port).</summary>
        private static string Endpoint(string s)
        {
            if (s.IndexOf('.') >= 0) return s;
            int colon = s.IndexOf(':');
            if (colon < 0) return s;
            return s.Substring(0, colon) + "." + s.Substring(colon + 1);
        }

        private static string Str(Dictionary<string, object> d, string key, string ctx)
        {
            object v;
            if (!d.TryGetValue(key, out v) || v == null) return null;
            string s = v as string;
            if (s == null)
                throw new WentaException("network JSON: " + ctx + ": '" + key + "' must be a string");
            return s;
        }

        private static bool IsNumber(object v)
        {
            return v is int || v is long || v is double || v is decimal
                || v is float || v is short || v is byte;
        }

        /// <summary>JavaScriptSerializer hands back Int32/Int64 for integral
        /// literals and Decimal for most fractional ones (Double only when the
        /// literal does not fit a Decimal). Decimal is re-parsed via its exact
        /// decimal string rather than cast, because the Decimal->Double cast
        /// rounds twice and is not guaranteed to reproduce the original
        /// double.</summary>
        private static double ToDouble(object v)
        {
            if (v is double) return (double)v;
            if (v is decimal)
                return double.Parse(((decimal)v).ToString(CultureInfo.InvariantCulture),
                                    NumberStyles.Float, CultureInfo.InvariantCulture);
            return Convert.ToDouble(v, CultureInfo.InvariantCulture);
        }

        private static double RequireDouble(Dictionary<string, object> d, string key, string ctx)
        {
            object v;
            if (!d.TryGetValue(key, out v) || v == null || !IsNumber(v))
                throw new WentaException("network JSON: " + ctx + " has no numeric '" + key + "'");
            return ToDouble(v);
        }

        private static double OptionalDouble(Dictionary<string, object> d, string key, double fallback, string ctx)
        {
            object v;
            if (!d.TryGetValue(key, out v) || v == null) return fallback;
            if (!IsNumber(v))
                throw new WentaException("network JSON: " + ctx + ": '" + key + "' must be a number");
            return ToDouble(v);
        }

        private static int ParseVersion(object v)
        {
            if (v == null || v is string || v is bool)
                throw new WentaException("network JSON: 'schema_version' must be a positive integer");
            double d = ToDouble(v);
            if (d != Math.Floor(d) || d < 1.0 || d > int.MaxValue)
                throw new WentaException("network JSON: 'schema_version' must be a positive integer, got "
                    + d.ToString("R", CultureInfo.InvariantCulture));
            return (int)d;
        }
    }
}
